// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwTMywF2b0Vddj_nd2hP9Rw7f1F3dyyUE',
    appId: '1:207015743190:web:431ea472cd1892df6b0377',
    messagingSenderId: '207015743190',
    projectId: 'budgetrack-d1f97',
    authDomain: 'budgetrack-d1f97.firebaseapp.com',
    storageBucket: 'budgetrack-d1f97.firebasestorage.app',
    measurementId: 'G-7CZV4N1XLF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_ITSx8LEdScBM46WreGZUEViSfV2ljbw',
    appId: '1:207015743190:android:260f8fa8496d4b886b0377',
    messagingSenderId: '207015743190',
    projectId: 'budgetrack-d1f97',
    storageBucket: 'budgetrack-d1f97.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwTMywF2b0Vddj_nd2hP9Rw7f1F3dyyUE',
    appId: '1:207015743190:web:d8316c6c5f4bdded6b0377',
    messagingSenderId: '207015743190',
    projectId: 'budgetrack-d1f97',
    authDomain: 'budgetrack-d1f97.firebaseapp.com',
    storageBucket: 'budgetrack-d1f97.firebasestorage.app',
    measurementId: 'G-C4QPXWMSK8',
  );
}
